# Generated by Django 5.1.3 on 2024-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NolaListing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Unnamed Property', max_length=255),
        ),
    ]
