# Generated by Django 5.1.3 on 2024-12-27 21:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NolaListing', '0004_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
